#!/usr/bin/env bash
set -euo pipefail

echo "=== GCP + direnv Auto-Switch Setup ==="
echo ""

# --- Prompt for work config ---
echo "-- Work GCP Configuration --"
read -p "Work email (e.g. you@company.com): " WORK_EMAIL
read -p "Work project ID: " WORK_PROJECT
read -p "Work directory (absolute path, e.g. /Users/braydntanner/summaft): " WORK_DIR
read -p "Work region [us-central1]: " WORK_REGION
WORK_REGION="${WORK_REGION:-us-central1}"

echo ""

# --- Prompt for personal config ---
echo "-- Personal GCP Configuration --"
read -p "Personal email (e.g. you@gmail.com): " PERSONAL_EMAIL
read -p "Personal project ID: " PERSONAL_PROJECT
read -p "Personal directory (absolute path, e.g. /Users/braydntanner/projects): " PERSONAL_DIR
read -p "Personal region [us-central1]: " PERSONAL_REGION
PERSONAL_REGION="${PERSONAL_REGION:-us-central1}"

echo ""

# --- Check prerequisites ---
if ! command -v gcloud &>/dev/null; then
  echo "ERROR: gcloud CLI not found. Install it first: https://cloud.google.com/sdk/docs/install"
  exit 1
fi

if ! command -v direnv &>/dev/null; then
  echo "ERROR: direnv not found. Install it first: brew install direnv"
  exit 1
fi

# --- Ensure direnv hook is in shell rc ---
SHELL_RC=""
case "$SHELL" in
  */zsh)  SHELL_RC="$HOME/.zshrc" ;;
  */bash) SHELL_RC="$HOME/.bashrc" ;;
  *)      SHELL_RC="$HOME/.zshrc" ;;
esac

if ! grep -q 'eval "$(direnv hook' "$SHELL_RC" 2>/dev/null; then
  echo "Adding direnv hook to $SHELL_RC..."
  echo '' >> "$SHELL_RC"
  echo '# direnv' >> "$SHELL_RC"
  echo 'eval "$(direnv hook zsh)"' >> "$SHELL_RC"
  echo "Added. You'll need to restart your shell or run: source $SHELL_RC"
else
  echo "direnv hook already in $SHELL_RC"
fi

echo ""

# --- Create gcloud configurations and authenticate ---
echo "Setting up gcloud configurations..."

# Work
echo ""
echo "-- Setting up WORK config --"
if gcloud config configurations describe work &>/dev/null 2>&1; then
  echo "gcloud config 'work' already exists, updating..."
  gcloud config configurations activate work
else
  gcloud config configurations create work
fi
gcloud config set account "$WORK_EMAIL"

# Authenticate before setting project/region (requires valid creds)
if gcloud auth print-access-token &>/dev/null 2>&1; then
  echo "Work account ($WORK_EMAIL) already authenticated."
else
  echo "Logging in to work account ($WORK_EMAIL)..."
  gcloud auth login "$WORK_EMAIL"
fi

gcloud config set project "$WORK_PROJECT"
gcloud config set compute/region "$WORK_REGION"

read -p "Set up Application Default Credentials for work? [y/N]: " WORK_ADC
if [[ "$WORK_ADC" =~ ^[Yy]$ ]]; then
  gcloud auth application-default login
fi

# Personal
echo ""
echo "-- Setting up PERSONAL config --"
if gcloud config configurations describe personal &>/dev/null 2>&1; then
  echo "gcloud config 'personal' already exists, updating..."
  gcloud config configurations activate personal
else
  gcloud config configurations create personal
fi
gcloud config set account "$PERSONAL_EMAIL"

# Authenticate before setting project/region (requires valid creds)
if gcloud auth print-access-token &>/dev/null 2>&1; then
  echo "Personal account ($PERSONAL_EMAIL) already authenticated."
else
  echo "Logging in to personal account ($PERSONAL_EMAIL)..."
  gcloud auth login "$PERSONAL_EMAIL"
fi

gcloud config set project "$PERSONAL_PROJECT"
gcloud config set compute/region "$PERSONAL_REGION"

read -p "Set up Application Default Credentials for personal? [y/N]: " PERSONAL_ADC
if [[ "$PERSONAL_ADC" =~ ^[Yy]$ ]]; then
  gcloud auth application-default login
fi

# Reset to default
gcloud config configurations activate default 2>/dev/null || true

echo ""

# --- Create .envrc files ---
echo "Creating .envrc files..."

# Work
mkdir -p "$WORK_DIR"
cat > "$WORK_DIR/.envrc" <<EOF
# GCP Work Config - auto-generated by setup-gcp-direnv.sh
export CLOUDSDK_ACTIVE_CONFIG_NAME="work"
export CLOUDSDK_CORE_PROJECT="$WORK_PROJECT"
export CLOUDSDK_CORE_ACCOUNT="$WORK_EMAIL"
export CLOUDSDK_COMPUTE_REGION="$WORK_REGION"
EOF

# Personal
mkdir -p "$PERSONAL_DIR"
cat > "$PERSONAL_DIR/.envrc" <<EOF
# GCP Personal Config - auto-generated by setup-gcp-direnv.sh
export CLOUDSDK_ACTIVE_CONFIG_NAME="personal"
export CLOUDSDK_CORE_PROJECT="$PERSONAL_PROJECT"
export CLOUDSDK_CORE_ACCOUNT="$PERSONAL_EMAIL"
export CLOUDSDK_COMPUTE_REGION="$PERSONAL_REGION"
EOF

# --- Allow direnv in both directories ---
echo "Allowing direnv in both directories..."
direnv allow "$WORK_DIR"
direnv allow "$PERSONAL_DIR"

# Reset to default
gcloud config configurations activate default 2>/dev/null || true

echo ""
echo "=== Setup Complete ==="
echo ""
echo "How it works:"
echo "  cd $WORK_DIR     -> auto-switches to work GCP ($WORK_EMAIL)"
echo "  cd $PERSONAL_DIR -> auto-switches to personal GCP ($PERSONAL_EMAIL)"
echo ""
echo "All subdirectories inherit the parent .envrc automatically."
echo ""
echo "Verify with:  cd <dir> && gcloud config configurations list"
